# Generated by Django 5.1 on 2024-09-01 15:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_perfilusuario_atualizado_em_perfilusuario_criado_em_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='saldocriptomoedas',
            name='criado_em',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
